"""empty message

Revision ID: 0ff8bfb9f710
Revises: a957d9b15445
Create Date: 2020-12-26 15:46:01.429481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff8bfb9f710'
down_revision = 'a957d9b15445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('delete_status', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'delete_status')
    # ### end Alembic commands ###
