"""empty message

Revision ID: 1321bd78a327
Revises: a1bdd731758a
Create Date: 2021-02-22 16:09:48.085693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1321bd78a327'
down_revision = 'a1bdd731758a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('upload_frequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'upload_frequency')
    # ### end Alembic commands ###
