"""add devices into task table.

Revision ID: 16451214fd60
Revises: 6fe209e1ce5c
Create Date: 2020-12-28 11:44:06.284847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16451214fd60'
down_revision = '6fe209e1ce5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('devices', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'devices')
    # ### end Alembic commands ###
