"""empty message

Revision ID: 34c0638687b6
Revises: 7a57b010ad80
Create Date: 2021-01-06 14:59:30.422988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '34c0638687b6'
down_revision = '7a57b010ad80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('device_ip', sa.String(length=50), nullable=True),
    sa.Column('device_kind', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=50), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('device_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_info',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_ip', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('device_kind', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('device_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='device_info_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('devices')
    # ### end Alembic commands ###
