"""empty message

Revision ID: 6fe209e1ce5c
Revises: 0ff8bfb9f710
Create Date: 2020-12-26 15:46:59.493875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fe209e1ce5c'
down_revision = '0ff8bfb9f710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_status', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'task_status')
    # ### end Alembic commands ###
