"""empty message

Revision ID: 9ffaf1645edc
Revises: 16451214fd60
Create Date: 2021-01-05 14:28:48.027191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffaf1645edc'
down_revision = '16451214fd60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('client_kind', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=50), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_info')
    # ### end Alembic commands ###
