"""change device info

Revision ID: a1bdd731758a
Revises: 34c0638687b6
Create Date: 2021-02-03 16:10:17.070564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1bdd731758a'
down_revision = '34c0638687b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'device_ip',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('devices', 'device_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_name', mysql.VARCHAR(length=50), nullable=False))
    op.alter_column('devices', 'device_ip',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
