"""empty message

Revision ID: a3748cc49a90
Revises: 9ffaf1645edc
Create Date: 2021-01-06 13:22:27.632840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3748cc49a90'
down_revision = '9ffaf1645edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('certificate', sa.Integer(), nullable=True))
    op.drop_column('tasks', 'devices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('devices', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('tasks', 'certificate')
    # ### end Alembic commands ###
